# Generated by Django 3.2.5 on 2021-08-02 07:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import srcprojectapp.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that Email address already exists'}, max_length=255, unique=True, verbose_name='Email Address')),
                ('mob_number', models.CharField(blank=True, error_messages={'unique': 'A user with that phone number address already exists'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number ', regex='^(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Phone Number ')),
                ('first_name', models.CharField(max_length=300, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last Name')),
                ('user_type', models.CharField(max_length=300, verbose_name='User Type')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profile',
                'ordering': ['email'],
            },
            managers=[
                ('objects', srcprojectapp.managers.UserManager()),
            ],
        ),
    ]
